[package]
name = "gpg_rust_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "gpg_rust_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
gpgme = "0.11.0"
rustler = "0.26.0"

[profile.release]
opt-level = "z"
